GIT CLEAN COMMAND DELETES YOUR WORKING AREA, it deletes codes and changes in workin area
GIT RESET WILL RE-ESTABLISH YOU AREA AS BASE
GIT REVERT WILL RESTORE YOU SYSTEM TO DEFAULT 
THESE COMMANDS KEEPS THE SYSTEM CLEAN
